info:
  project:
    name: Vert.x Start
    version: 0.1.0
  # remember to update static/install.sh as well:
  spring-boot:
    version: 3.2.0

server:
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048

initializr:
  description:
    value: Demo project for Vert.x
  env:
    spring-boot-metadata-url:
  dependencies:
    - name: Core
      content:
        - name: Vert.x Core
          id: vertx-core
          groupId: io.vertx
          artifactId: vertx-core
          description: Vert.x core contains fairly low level functionality including support for HTTP, TCP, file system access, and various other features.
          starter: false
    - name: Web
      content:
        - name: Vert.x Web
          id: vertx-web
          groupId: io.vertx
          artifactId: vertx-web
          description: Vert.x Web is a toolkit for writing sophisticated modern web applications and HTTP microservices.
          starter: false
        - name: Vert.x Thymeleaf Web
          id: vertx-web-templ-thymeleaf
          groupId: io.vertx
          artifactId: vertx-web-templ-thymeleaf
          description: Vert.x Thymeleaf Web.
          starter: false
        - name: Vert.x Handlebars Web
          id: vertx-web-templ-handlebars
          groupId: io.vertx
          artifactId: vertx-web-templ-handlebars
          description: Vert.x Handlebars Web.
          starter: false
        - name: Vert.x Jade Web
          id: vertx-web-templ-jade
          groupId: io.vertx
          artifactId: vertx-web-templ-jade
          description: Vert.x Jade Web.
          starter: false
        - name: Vert.x Mvel Web
          id: vertx-web-templ-mvel
          groupId: io.vertx
          artifactId: vertx-web-templ-mvel
          description: Vert.x Mvel Web.
          starter: false
    - name: Reactive
      content:
        - name: Vert.x Rx
          id: vertx-rx-java
          groupId: io.vertx
          artifactId: vertx-rx-java
          description: Vert.x provides Rx-ified (using RxJava) versions for most of its APIs so you can use those if you prefer.
          starter: false
        - name: Vert.x Reactive Streams
          id: vertx-reactive-streams
          groupId: io.vertx
          artifactId: vertx-reactive-streams
          description: Vert.x supports reactive streams so your applications can interoperate with other reactive systems such as Akka or Project Reactor.
          starter: false
        - name: Vert.x Sync
          id: vertx-sync
          groupId: io.vertx
          artifactId: vertx-sync
          description: Vert.x allows you to deploy verticles that run using fibers. Fibers are very lightweight threads that can be blocked without blocking a kernel thread. This enables you to write your verticle code in a familiar synchronous style.
          starter: false
    - name: Data Access
      content:
        - name: Vert.x Mongodb Client
          id: vertx-mongo-client
          groupId: io.vertx
          artifactId: vertx-mongo-client
          description: Vert.x Mongodb Client allows applications to interact with a MongoDB instance, whether that’s saving, retrieving, searching, or deleting documents.
          starter: false
        - name: Vert.x Mongodb Embedded Db
          id: vertx-mongo-embedded-db
          groupId: io.vertx
          artifactId: vertx-mongo-embedded-db
          description: Vert.x Mongodb Embedded Db.
          starter: false
        - name: Vert.x JDBC Client
          id: vertx-jdbc-client
          groupId: io.vertx
          artifactId: vertx-jdbc-client
          description: Vert.x JDBC Client allows you to interact with any JDBC compliant database using an asynchronous API from your Vert.x application.
          starter: false
        - name: Vert.x Common SQL
          id: vertx-sql-common
          groupId: io.vertx
          artifactId: vertx-sql-common
          description: Vert.x Common SQL is used to interact with Vert.x SQL services.
          starter: false
        - name: Vert.x Redis Client
          id: vertx-redis-client
          groupId: io.vertx
          artifactId: vertx-redis-client
          description: Vert.x Redis Client allows applications to interact with a Redis instance, whether that’s saving, retrieving, searching, or deleting documents.
          starter: false
    - name: Integration
      content:
        - name: Vert.x Mail Client
          id: vertx-mail-client
          groupId: io.vertx
          artifactId: vertx-mail-client
          description: Vert.x Mail Client provides a simple SMTP mail client so you can send emails from your applications.
          starter: false
        - name: Vert.x Mail Service
          id: vertx-mail-service
          groupId: io.vertx
          artifactId: vertx-mail-service
          description: Vert.x Mail Service.
          starter: false
        - name: Vert.x Stomp
          id: vertx-stomp
          groupId: io.vertx
          artifactId: vertx-stomp
          description: Vert.x Stomp provides an implementation of the STOMP protocol.
          starter: false
        - name: Vert.x JCA Adaptor
          id: vertx-jca
          groupId: io.vertx
          artifactId: vertx-jca
          description: Vert.x provides a Java Connector Architecture (JCA) adaptor which allows it to interoperate with any JavaEE application server.
          starter: false
        - name: Vert.x TCP Eventbus Bridge
          id: vertx-tcp-eventbus-bridge
          groupId: io.vertx
          artifactId: vertx-tcp-eventbus-bridge
          description: An eventbus bridge that let you interact with vert.x from any application thanks to a TCP socket.
          starter: false
    - name: Authentication and Authorisation
      content:
        - name: Vert.x Common Auth APIs
          id: vertx-auth-common
          groupId: io.vertx
          artifactId: vertx-auth-common
          description: Vert.x Common Auth APIs provides interfaces for authentication and authorisation that can be used from your Vert.x applications and can be backed by different providers.
          starter: false
        - name: Vert.x JDBC Auth Provider implementation
          id: vertx-auth-jdbc
          groupId: io.vertx
          artifactId: vertx-auth-jdbc
          description: Vert.x JDBC Auth Provider provides an implementation of AuthProvider which uses the Vert.x JDBCClient to perform authentication and authorisation against any JDBC compliant database.
          starter: false
        - name: Vert.x JWT auth
          id: vertx-auth-jwt
          groupId: io.vertx
          artifactId: vertx-auth-jwt
          description: Vert.x JWT Auth contains an out of the box a JWT implementation.
          starter: false
        - name: Vert.x OAuth2
          id: vertx-auth-oauth2
          groupId: io.vertx
          artifactId: vertx-auth-oauth2
          description: Vert.x OAuth2 Auth contains an out of the box a OAuth2 implementation.
          starter: false
        - name: Vert.x Shiro
          id: vertx-auth-shiro
          groupId: io.vertx
          artifactId: vertx-auth-shiro
          description: Vert.x Shiro Provider contains an implementation that uses Apache Shiro.
          starter: false
        - name: Vert.x Mongo Auth
          id: vertx-auth-mongo
          groupId: io.vertx
          artifactId: vertx-auth-mongo
          description: Vert.x Mongo Auth Provider provides an implementation of AuthProvider which uses the Vert.x MongoDbClient to perform authentication and authorisation against MongoDb database.
          starter: false
    - name: Devops
      content:
        - name: Vert.x Dropwizard
          id: vertx-dropwizard-metrics
          groupId: io.vertx
          artifactId: vertx-dropwizard-metrics
          description: Vert.x Dropwizard captures metrics from Vert.x core components and exposes them using Dropwizard.
          starter: false
        - name: Vert.x Hawkular Metrics
          id: vertx-hawkular-metrics
          groupId: io.vertx
          artifactId: vertx-hawkular-metrics
          description: Vert.x Hawkular  is an implementation of the Vert.x Metrics Service Provider Interface (SPI) i.e. metrics built from Vert.x events will be sent to Hawkular, an open source monitoring and management solution.
          starter: false
        - name: Vert.x Shell
          id: vertx-shell
          groupId: io.vertx
          artifactId: vertx-shell
          description: Vert.x Shell lets you interact with your vert.x application using a CLI interface.
          starter: false
    - name: Clustering
      content:
        - name: Vert.x Hazelcast
          id: vertx-hazelcast
          groupId: io.vertx
          artifactId: vertx-hazelcast
          description: Vert.x Hazelcast is a cluster manager implementation for Vert.x that uses Hazelcast.
          starter: false
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: starter.zip
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      sts-id: gradle.zip
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
    - name: Gradle Config
      id: gradle-build
      description: Generate a Gradle build file
      sts-id: build.gradle
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
  packagings:
    - name: Jar
      id: jar
      default: true
  javaVersions:
    - id: 1.8
      default: true
  languages:
    - name: Java
      id: java
      default: true
    - name: Groovy
      id: groovy
      default: false
  bootVersions:
    - name : 3.2.0
      id: 3.2.0
      default: true
